### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Yenthe666** [odoo-vertical-hosting/odoo-hosting-orchestrator#2]
Go to SaaS > SaaS > Servers and create a new server.
Fill in the following values:
Domain name:http://www.yourdomain.com
IP:192.168.xxx.xxx
SSH port:22
Start Port: 8069
End Port: 8070

Click on save
You will now get the following error: 
<img src="http://i.imgur.com/QWq3HXS.png" alt="Error" />

The record will not be saved either.

**Comment by YannickB** [comment]
Ah yes of course. You need to specify the odoo install path in the saas configuration. You need to indicate the path to the orchestrator addons, so it can resolve $odoo_path/saas/shell/sed.sh.

Of course I'm not satisfied by this, I'll try to improve it during the refactoring.

**Comment by Yenthe666** [comment]
@YannickB perhaps, if you can not fix this with refactoring, you could just show a plain warning pop-up which says something like 'Please configure the Odoo install path for the SaaS configuration'?
Then the user would atleast have an idea about whats up :)

**Comment by YannickB** [comment]
Yes indeed, this will be a good fallback.

I wonder if there is a buildt-in function in Odoo to get the path of a specific module. If yes, I'll not need this configuration field anymore. I let the ticket open until I resolve it, thanks for the feedback.

**Comment by YannickB** [comment]
No it'll not make it since I have several value in addons_path. That said, maybe I can test all of them, I'll see.

**Comment by Yenthe666** [comment]
Alright keep me updated and best of luck!

**Comment by YannickB** [comment]
Done, I found the function modules.get_module_path() which do just what I needed. I removed the configuration path. I close the issue.

**Comment by Yenthe666** [comment]
Well that was an easy and fast fix. Awesome, keep up the good work.
